tokenizer_name_or_path: src/tok_library/data/tokenizer/tokenizer.json #  "../data/tokenizer/tokenizer.json"
eos_token: "<|end_of_text|>"
output_folder: "example_scripts/example_processed_data"
logging_dir: "example_scripts/example_processed_data"
n_tasks: 1
n_workers: -1
shuffle: false
tokenizer_batch_size: 10

# Dataset options
reader: "parquet"
dataset: "src/tok_library/data/ItalianPD_1.parquet"
column: "text"
split: "train"
glob_pattern: null

# Slurm options
slurm: false
partition: null
qos: null
time: "20:00:00"
email: null
cpus_per_task: 1
mem_per_cpu_gb: 2